dado = input("Digite algo: ")
print(type(dado))
print("São letras?", dado.isalpha())
print("É um número?", dado.isalnum())
print("É alfanumérico?", dado.isascii())
print("É decimal?", dado.isdecimal())
print("É um dígito?", dado.isdigit())
print("É um identificador?", dado.isidentifier())
print("Está todo em minúsculas?", dado.islower())
print("É numérico?", dado.isnumeric())
print("É printável?", dado.isprintable())
print("É espaço?", dado.isspace())
print("É um título?", dado.istitle())
print("Está todo em maiúsculas?", dado.isupper())